[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
composite_vault = "HxGs1wgKnbVgC2FxqmgN7RcpuuaePbQUT5g3bNYBrPAo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "npm test"

[test]
startup_wait = 10000